using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ExcelToFlatBuffer
{
    public class Template_Server_Java_Json
    {
        public static string Template_Manager =
@"// Generated by the table tool compiler.  DO NOT EDIT!

package com.cyou.fusion.table.data;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import gnu.trove.iterator.TIntObjectIterator;
import gnu.trove.map.hash.TIntObjectHashMap;
import com.cyou.fusion.table.core.TableUtility;

import java.util.ArrayList;

public class TableManager {{

    private static final Logger logger = LoggerFactory.getLogger(TableManager.class);
{0}

    public static boolean initTable(){{
{1}
        return true;
    }}
}}
";
        public static string Template_ManagerSingleTableCode =
@"    private static ArrayList<Table{0}> g{1}Array = null;
    private static TIntObjectHashMap<Table{2}> g{3}Map = new TIntObjectHashMap<Table{2}>();

    private static boolean initTable{4}() {{
        try {{
            g{5}Map.clear();
            g{6}Array = TableUtility.LoadJsonTable(""{7}.json"", Table{8}.class);
            for (Table{9} table : g{10}Array) {{
                g{11}Map.put(table.getId(), table);
            }}
        }} catch (Exception e) {{
            e.printStackTrace();
            return false;
        }}
        return true;
    }}

    public static final Table{12} get{13}ByID(int nKey){{
        return g{14}Map.get(nKey);
    }}

    public static final Table{15} get{16}ByIndex(int nIdx){{
        return g{17}Array.get(nIdx);
    }}

    public static final int get{18}Size(){{
        return g{19}Array.size();
    }}

    public static final TIntObjectIterator<Table{20}> get{21}ByIterator() {{
        return g{22}Map.iterator();
    }}
";

        public static string Template_ManagerSingleTableCodeInit =
@"        if (!initTable{0}()){{
           logger.error(""load table {1} error!"");
           return false;
        }}
";

        public static string Template_SingleTableCode =
@"// Generated by the table tool compiler.  DO NOT EDIT!

package com.cyou.fusion.table.data;

import com.fasterxml.jackson.annotation.JsonProperty;

public class TableLevelTarget {{

{0}

{1}

}}";

        public static string Template_SingleTableCodeWord =
@"     @JsonProperty(""{0}"")
     private int m{1};
";

        public static string Template_SingleTableCodeWordGet =
@"    public int get{0}(){{
        return this.m{1};
    }}
";

        public static string Template_Json = 
@"[
{0}
]
";
        public static string Template_JsonCell =
@"""{0}"": {1},";





    }






}
